export const NOTIFICATION_TYPES = Object.freeze({
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  CREDIT_DUE: 'CREDIT_DUE',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PURCHASE_RECEIVED: 'PURCHASE_RECEIVED',
  SYSTEM: 'SYSTEM',
});
