export const PURCHASE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
});

export const SALE_STATUS = Object.freeze({
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const DELIVERY_STATUS = Object.freeze({
  PENDING: 'PENDING',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
});

export const STOCK_MOVEMENT_TYPE = Object.freeze({
  OPENING: 'OPENING',
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  CUSTOMER_RETURN: 'CUSTOMER_RETURN',
  SUPPLIER_RETURN: 'SUPPLIER_RETURN',
  DAMAGE: 'DAMAGE',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  CANCELLATION_REVERSAL: 'CANCELLATION_REVERSAL',
});

export const ADJUSTMENT_TYPE = Object.freeze({
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
});
