import multer from 'multer';
import path from 'path';
import fs from 'fs';

/**
 * Local-disk multer storage, organized by purpose (products/invoices/profiles/temp).
 * For production, swap the storage engine here for `multer-storage-cloudinary`
 * (cloudinary.js below already exports a configured client) without touching
 * any controller code — they only depend on `req.file`/`req.files`.
 */
const UPLOAD_ROOT = path.resolve('uploads');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function makeStorage(subfolder) {
  const dir = path.join(UPLOAD_ROOT, subfolder);
  ensureDir(dir);
  return multer.diskStorage({
    destination: (req, file, cb) => cb(null, dir),
    filename: (req, file, cb) => {
      const uniqueSuffix = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
      cb(null, `${uniqueSuffix}${path.extname(file.originalname)}`);
    },
  });
}

const imageFileFilter = (req, file, cb) => {
  const allowed = ['image/jpeg', 'image/png', 'image/webp'];
  if (!allowed.includes(file.mimetype)) {
    return cb(new Error('Only JPEG, PNG, or WEBP images are allowed'));
  }
  cb(null, true);
};

export const productImageUpload = multer({
  storage: makeStorage('products'),
  fileFilter: imageFileFilter,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB
});

export const profileImageUpload = multer({
  storage: makeStorage('profiles'),
  fileFilter: imageFileFilter,
  limits: { fileSize: 2 * 1024 * 1024 }, // 2MB
});

export const invoiceUpload = multer({
  storage: makeStorage('invoices'),
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB — PDFs generated by reportService
});

export const tempUpload = multer({ storage: makeStorage('temp') });
